MVC/WebShop/Controllers/BrandController.cs
using System;
using System.Web.Mvc;
using Interfaces.Interfaces;
using WebShop.Filters;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class BrandController : Controller
    {
        private readonly IBrandService _service;

        public BrandController(IBrandService service)
        {
            _service = service;
        }

        public ActionResult Index()
        {
            var brands = _service.GetAll();
            return PartialView(brands);
        }

        public ActionResult Details(int id)
        {
            var brand = _service.Get(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return PartialView(brand);
        }

        [UserAuthorize(Roles = "admin")]
        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorize(Roles = "admin")]
        public ActionResult Create(BrandVM brand)
        {
            if (ModelState.IsValid)
            {
                return PartialView("Create", brand);
            }

            try
            {
                _service.Create(brand.Brand);
                return RedirectToAction("Index", "Common");
            }
            catch
            {
                return RedirectToAction("Index", "Common");
            }
        }

        [UserAuthorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            var brand = _service.Get(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return PartialView(new BrandVM(brand));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorize(Roles = "admin")]
        public ActionResult Edit(BrandVM brand)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("Edit", brand);
            }

            try
            {
                _service.Update(brand.Brand);
                return RedirectToAction("Index", "Common");
            }
            catch
            {
                return RedirectToAction("Index", "Common");
            }
        }

        [HttpPost]
        [UserAuthorize(Roles = "admin")]
        public JsonResult Delete(int id)
        {
            try
            {
                _service.Delete(id);
                return Json(new {success = true, data = "You deleted the item"}, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new {success = false, data = e.Message}, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

MVC/WebShop/Controllers/CategoryController.cs
using System;
using System.Web.Mvc;
using Interfaces.Interfaces;
using WebShop.Filters;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _service;

        public CategoryController(ICategoryService service)
        {
            _service = service;
        }

        public ActionResult Common()
        {
            return View();
        }

        public ActionResult Index()
        {
            var category = _service.GetAll();
            return PartialView(category);
        }

        public ActionResult Details(int id)
        {
            var category = _service.Get(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return PartialView(category);
        }

        [UserAuthorize(Roles = "admin")]
        public ActionResult Create()
        {
            return PartialView(new CategoryVM());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorize(Roles = "admin")]
        public ActionResult Create(CategoryVM category)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("Create", category);
            }
            try
            {
                _service.Create(category.Category);
                return RedirectToAction("Index", "Common");
            }
            catch
            {
                return RedirectToAction("Index", "Common");
            }
        }

        [UserAuthorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            var category = _service.Get(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return PartialView(new CategoryVM(category));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorize(Roles = "admin")]
        public ActionResult Edit(CategoryVM category)
        {
            try
            {
                _service.Update(category.Category);
                return RedirectToAction("Index", "Common");
            }
            catch
            {
                return RedirectToAction("Index", "Common");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorize(Roles = "admin")]
        public JsonResult Delete(int id)
        {
            try
            {
                _service.Delete(id);
                return Json(new {success = true, data = "You deleted the item"}, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new {success = false, data = e.Message}, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

MVC/WebShop/Controllers/CommonController.cs
using System.Web.Mvc;

namespace WebShop.Controllers
{
    public class CommonController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC/WebShop/Views/Category/Common.cshtml
@{
    ViewBag.Title = "Common";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-6" id="category-view">
        @Html.Action("Index", "Category")
    </div>
    <div class="col-md-6" id="brand-view">
        @Html.Action("Index", "Brand")
    </div>
</div>
<div id="mod-dialog" class="modal fade">
    <div id="dialog-content" class="modal-dialog"></div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/WebShop/Views/Category/Create.cshtml
@model WebShop.Models.CategoryVM

<div class="modal-content">
    <div class="modal-header">
        <h4 class="float-left">Edit</h4>
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <div class="modal-body">
        <span class="text-danger">@ViewBag.Error</span>
        @using (Html.BeginForm("Create", "Category", FormMethod.Post, new {id = "modal-form"}))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new {htmlAttributes = new {@class = "form-control modal-text-area"}})
                        @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default"/>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

MVC/WebShop/Views/Category/Details.cshtml
@model BLL.Models.Models.CategoryDTO

<div class="modal-content">
    <div class="modal-header">
        <h4 class="float-left">Details</h4>
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <div class="modal-body">
        <div>
            <b>Name</b>
            <p>@Html.DisplayFor(model => model.Name)</p>

            <b>Description</b>
            <p>@Model.Description</p>
        </div><div>
            <b>Name</b>
            <p>@Html.DisplayFor(model => model.Name)</p>

            <b>Description</b>
            <p>@Model.Description</p>
        </div>
    </div>
</div>

MVC/WebShop/Views/Category/Edit.cshtml
@model WebShop.Models.CategoryVM


<div class="modal-content">
    <div class="modal-header">
        <h4 class="float-left">Edit</h4>
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <div class="modal-body">
        <span class="text-danger">@ViewBag.Error</span>
        @using (Html.BeginForm("Edit", "Category", FormMethod.Post, new {id = "modal-form"}))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new {htmlAttributes = new {@class = "form-control modal-text-area"}})
                        @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Edit" class="btn btn-default"/>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

MVC/WebShop/Views/Category/Index.cshtml
@model IEnumerable<BLL.Models.Models.CategoryDTO>

@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create", null, new {@class = "dialog-link"})
    </p>
}

@foreach (var item in Model)
{
    <div class="border-top border-dark py-3">
        <a class ="dialog-link text-dark" href =@Url.RouteUrl("Default", new {controller = "Category", action = "Details", id = item.Id })>
            <div class="col-12">
                <b>Brand</b>
                <p>@item.Name</p>
            </div>
            <div class="col-12">
                <b>Description</b> <br/>
                <p class="d-inline-block text-truncate" style="max-width: 100%;">
                    @item.Description
                </p>
            </div>
        </a>
            @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
            {
                <div class="col-12">
                @Html.ActionLink("Edit", "Edit", new {id = item.Id}, new {@class = "dialog-link"}) |
                @Ajax.ActionLink("Delete", "Delete", new {id = item.Id}, new AjaxOptions
                {
                    Confirm = "Are sure wants to delete this item?",
                    HttpMethod = "POST",
                    OnComplete = "DeleteIsComplete"
                })
                </div>
            }
    </div>
}