MVC/WebShop/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BLL.Models.Models;
using Interfaces.Interfaces;
using WebShop.Filters;
using WebShop.Models;
using WebShop.Models.Helpers;

namespace WebShop.Controllers
{
    public class ImageController : Controller
    {
        private readonly IImageService _service;

        public ImageController(IImageService service)
        {
            _service = service;
        }

        public ActionResult Index(string product)
        {
            var images = new List<ImageVM>();
            images = GetProductsImages(Guid.Parse(product)).ToList();
            return View(images);
        }

        public ActionResult ProductCardImage(string product)
        {
            var image = new ImageDTO();
            image = _service.Get(Guid.Parse(product));
            return PartialView(image != null ? new ImageVM(image) : new ImageVM());
        }

        [UserAuthorize(Roles = "admin")]
        public PartialViewResult GetImages(string product)
        {
            var images = GetProductsImages(Guid.Parse(product)).ToList();
            return PartialView(images);
        }

        [HttpPost]
        [UserAuthorize(Roles = "admin")]
        public ActionResult CreateImage(ImageVM imageVm)
        {
            var image = imageVm.GetImageDto();
            try
            {
                _service.Create(image);
                return Json(new {success = true, data = $"{image.Name.ToString()}"},
                    JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new {success = false},
                    JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [UserAuthorize(Roles = "admin")]
        public JsonResult Delete(string number)
        {
            try
            {
                _service.Delete(Guid.Parse(number));
                return Json(new {success = true, responseText = $"{number}"}, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new {success = false, responseText = $"You could not remove the image № {number}"},
                    JsonRequestBehavior.AllowGet);
            }
        }

        private IEnumerable<ImageVM> GetProductsImages(Guid product)
        {
            var images = _service.Find(product);
            return images.Select(img => new ImageVM(img)).ToList();
        }
    }
}

MVC/WebShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BLL.Models.Models;
using Interfaces.Interfaces;
using WebShop.Filters;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly IBrandService _brandService;
        private readonly ICategoryService _categoryService;
        private readonly int _pageSize = 3;
        private readonly IProductService _service;

        public ProductController(IProductService service, ICategoryService categoryService, IBrandService brandService)
        {
            _service = service;
            _categoryService = categoryService;
            _brandService = brandService;
        }

        public ActionResult List(string category = null, string brand = null, int page = 1)
        {
            var items = _service.GetPage((page - 1) * _pageSize, _pageSize, category, brand);
            var totalCount = _service.Count(category, brand);
            var model = new PageListVM<ProductDTO>(items, page, _pageSize, totalCount);
            if (Request.IsAjaxRequest())
            {
                return PartialView("ListPartial", model);
            }

            return View(model);
        }

        public ActionResult Details(string number)
        {
            var product = _service.Get(Guid.Parse(number));
            if (product == null)
            {
                return HttpNotFound();
            }

            return View(product);
        }

        public PartialViewResult SelectCategory()
        {
            var category = _categoryService.GetAll().OrderBy(c => c.Name).Select(c => c.Name).ToList();
            return PartialView(category);
        }

        public PartialViewResult SelectBrand()
        {
            var category = _brandService.GetAll().OrderBy(c => c.Name).Select(c => c.Name).ToList();
            return PartialView(category);
        }

        [UserAuthorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.Categories = CategoriesSelect();
            ViewBag.Brands = BrandsSelect();
            return View();
        }

        [HttpPost]
        [UserAuthorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductVM productVM)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = CategoriesSelect();
                ViewBag.Brands = BrandsSelect();
                return View(productVM);
            }

            var product = productVM.Product;
            _service.Create(product);
            return RedirectToAction("List");
        }

        [UserAuthorize(Roles = "admin")]
        public ActionResult Edit(string number)
        {
            ViewBag.Categories = CategoriesSelect();
            ViewBag.Brands = BrandsSelect();
            var product = _service.Get(Guid.Parse(number));
            if (product == null)
            {
                return HttpNotFound();
            }

            return View(new ProductVM(product));
        }

        [HttpPost]
        [UserAuthorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductVM product)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = CategoriesSelect();
                ViewBag.Brands = BrandsSelect();
                return View(product);
            }

            _service.Update(product.Product);
            return RedirectToAction("List");
        }

        [HttpPost]
        [UserAuthorize(Roles = "admin")]
        public JsonResult Delete(string number)
        {
            try
            {
                _service.Delete(Guid.Parse(number));
                return Json(new {success = true, data = $"You deleted the product № {number}"},
                    JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new {success = false, data = $"You could not remove the product № {number}"},
                    JsonRequestBehavior.AllowGet);
            }
        }

        private IEnumerable<SelectListItem> CategoriesSelect()
        {
            return _categoryService.GetAll().Select(c => new SelectListItem {Text = c.Name, Value = c.Name});
        }

        private IEnumerable<SelectListItem> BrandsSelect()
        {
            return _brandService.GetAll().Select(b => new SelectListItem {Text = b.Name, Value = b.Name});
        }
    }
}

MVC/WebShop/Views/Product/Create.cshtml
@model WebShop.Models.ProductVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.HiddenFor(m => m.Number)
        @Html.LabelFor(model => model.Name, new {@class = "control-label"})
        @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control col-10"}})
        @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Description, new {@class = "control-label"})
        @Html.TextAreaFor(m => m.Description, new {@class = "form-control col-10", rows = "6", cols = "10"})
        @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cost, new {@class = "control-label"})

        @Html.EditorFor(model => model.Cost, new {htmlAttributes = new {@class = "form-control col-10"}})
        @Html.ValidationMessageFor(model => model.Cost, "", new {@class = "text-danger"})
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, new {@class = "control-label"})
        @Html.EditorFor(model => model.Quantity, new {htmlAttributes = new {@class = "form-control col-10"}})
        @Html.ValidationMessageFor(model => model.Quantity, "", new {@class = "text-danger"})
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryName, new {@class = "control-label"})
        @Html.DropDownListFor(p => p.CategoryName, (IEnumerable<SelectListItem>) ViewBag.Categories, new {@class = "form-control col-10"})
        @Html.ValidationMessageFor(model => model.CategoryName, "", new {@class = "text-danger"})
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BrandName, new {@class = "control-label"})
        @Html.DropDownListFor(p => p.BrandName, (IEnumerable<SelectListItem>) ViewBag.Brands, new {@class = "form-control col-10"})
        @Html.ValidationMessageFor(model => model.BrandName, "", new {@class = "text-danger"})
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
}
<div>
    @Html.ActionLink("Back to List", "List", "Product")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/WebShop/Views/Product/Details.cshtml
@model BLL.Models.Models.ProductDTO

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h4>@Model.Name</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        @Html.Action("Index", "Image", new { product = Model.Number })
    </div>
    <div class="col-md-6">
        <div>
            <h4><b>Category</b><span class="float-right">@Model.CategoryName</span></h4>
        </div>
        <div>
            <h4><b>Brand</b><span class="float-right"> @Model.BrandName</span></h4>
        </div>
        <label class="text-black-50">Description</label>
        <div class ="pb-5">
            @Model.Description
        </div>
        <div class="card-subtitle">
            <b>Quantity</b> <span class="float-right">@String.Format($"{Model.Quantity}") </span>
        </div>
        <div class="card-subtitle">
            <b>Price</b> <span class="float-right">@String.Format($"{Model.Cost:C}") </span>
        </div>
        @Html.Partial("AddToCart", Model, new ViewDataDictionary { { "returnUrl", Request.Path } })
        <p>Product Id: <span class="text-muted">@Model.Number</span></p>
    </div>
</div>

MVC/WebShop/Views/Product/Edit.cshtml
@using Microsoft.Ajax.Utilities
@model WebShop.Models.ProductVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Product</h2>
@using (Html.BeginForm())
{
    <div class="row">
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-md-6">
            <div class="form-group">
                @Html.HiddenFor(m => m.Number)
                @Html.LabelFor(model => model.Name, new {@class = "control-label"})
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control col-10"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, new {@class = "control-label"})
                @Html.TextAreaFor(m => m.Description, new {@class = "form-control col-10", rows = "6", cols = "10"})
                @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cost, new {@class = "control-label"})

                @Html.EditorFor(model => model.Cost, new {htmlAttributes = new {@class = "form-control col-10"}})
                @Html.ValidationMessageFor(model => model.Cost, "", new {@class = "text-danger"})
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, new {@class = "control-label"})
                @Html.EditorFor(model => model.Quantity, new {htmlAttributes = new {@class = "form-control col-10"}})
                @Html.ValidationMessageFor(model => model.Quantity, "", new {@class = "text-danger"})
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoryName, new {@class = "control-label"})
                @Html.DropDownListFor(p => p.CategoryName, (IEnumerable<SelectListItem>) ViewBag.Categories, new {@class = "form-control col-10"})
                @Html.ValidationMessageFor(model => model.CategoryName, "", new {@class = "text-danger"})
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BrandName, new {@class = "control-label"})
                @Html.DropDownListFor(p => p.BrandName, (IEnumerable<SelectListItem>) ViewBag.Brands, new {@class = "form-control col-10"})
                @Html.ValidationMessageFor(model => model.BrandName, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="col-md-6 p-2 border-light" id="img-list" style="overflow-y: scroll; max-height: 700px">
            @Html.Action("GetImages", "Image", new {product = Model.Number})
        </div>
    </div>
    <div class="row">
        <div class="form-group col-6">
            <input type="submit" value="Edit" class="btn btn-default" />
        </div>
        <div class="form-group col-4">
            <input type="file" id="img-load" value="Choose file" placeholder="Choose file" class="form-control" accept="image/x-png,image/jpeg">
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List", "Product")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function Image(data, product) {
            this.DataUrl = data;
            this.Product = product;
        }
        $('#img-load').change(
            function() {
                var reader = new FileReader();
                reader.onload = function(e) {
                    var img = new Image(e.target.result, "@Html.Raw(Model.Number)");
                    Save(img);
                    $('#img-load').val("");
                }
                reader.readAsDataURL(this.files[0]);
            });
        function Save(img) {
            $.ajax({
                type: "POST",
                url: "@Url.Action("CreateImage", "Image")",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify(img),
            }).done(function() {
                $('#img-list').load('@Url.Action("GetImages", "Image", new {product = Model.Number})')
            });
        }
    </script>
}

MVC/WebShop/Views/Product/ItemPartialView.cshtml
@model BLL.Models.Models.ProductDTO


<div class="col-lg-4 mb-2">
    <div class="card" id="@Model.Number.ToString()">
        @Html.Action("ProductCardImage", "Image", new {product = Model.Number})
        <div class="card-body">
            <h5 class="card-title">
                <a class="text-dark" href=@Url.RouteUrl("Product", new {number = Model.Number})>@Model.Name</a>
            </h5>
            <div>
                <h6>@Model.CategoryName</h6>
            </div>
            <div>
                <h6>@Model.BrandName</h6>
            </div>
            <div class="card-subtitle">
                <b>Quantity</b> <span class="float-right">@string.Format($"{Model.Quantity}") </span>
            </div>
            <div class="card-subtitle">
                <b>Price</b> <span class="float-right">@string.Format($"{Model.Cost:C}") </span>
            </div>
        </div>
        <div class="card-footer">
            @Html.Partial("AddToCart", Model)
            @if (User.IsInRole("admin"))
            {
                <div>
                    <a href=@Url.RouteUrl("EditProduct", new {number = Model.Number})> Edit</a>
                    @Ajax.ActionLink("Delete", "Delete", "Product", new {number = Model.Number}, new AjaxOptions
                    {
                        Confirm = "Are sure wants to delete this item?",
                        HttpMethod = "POST",
                        OnComplete = "DeleteIsComplete"
                    })
                </div>
            }
            <small class="text-muted d-block">@Model.Number</small>
        </div>
    </div>
</div>

MVC/WebShop/Views/Product/List.cshtml
@model WebShop.Models.PageListVM<BLL.Models.Models.ProductDTO>



@{
    ViewBag.Title = "Catalog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-3 col-sm-6">
           @Html.Action("SelectCategory")
            @Html.Action("SelectBrand")
    </div>
    <div class="col-md-9 col-sm-6" >
        <div id="ProductList">
            @if (@Model.Count == 0) {
                <p class="h3">
                    Sorry, nothing was found
                </p>
            }
            else
            {
                @Html.Partial("ListPartial", Model);
            }
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <div class="col fixed-bottom mb-5 mr-5">
                <button class="btn btn-primary float-right">
                    @Html.ActionLink("Create new..", "Create", "Product", null, new { @class = "text-dark" })
                </button>
            </div>
        }
    </div>
</div>

MVC/WebShop/Views/Product/ListPartial.cshtml
@using System.Text
@model WebShop.Models.PageListVM<BLL.Models.Models.ProductDTO>

@{
    var result = new StringBuilder();

    var i = 0;
    var row = new TagBuilder("div");


    foreach (var item in Model)
    {
        i++;
        if (i == 1)
        {
            row = new TagBuilder("div");
            row.AddCssClass("row");
        }

        row.InnerHtml += Html.Partial("ItemPartialView", item);

        if (i == 3)
        {
            result.Append(row);
        }
    }
    if (i != 3)
    {
        result.Append(row);
        i = 0;
    }

    @MvcHtmlString.Create(result.ToString())
}

@Html.Partial("PagePartial", Model)

MVC/WebShop/Views/Product/PagePartial.cshtml
@using System.Text
@model WebShop.Models.PageListVM<BLL.Models.Models.ProductDTO>


@{
    var categoryName = HttpContext.Current.Request.QueryString.Get("category");
    var brandName = HttpContext.Current.Request.QueryString.Get("brand");

    var liItem = new TagBuilder("li");
    var html = new StringBuilder();

    liItem.InnerHtml = Ajax.ActionLink("Prev", "List", new {category = categoryName, brand = brandName, page = Model.CurrentPage - 1},
        new AjaxOptions {InsertionMode = InsertionMode.Replace, UpdateTargetId = "ProductList"},
        new {@class = "page-link ajax-page-link"}
        ).ToString();
    liItem.AddCssClass("page-item");


    if (Model.CurrentPage == 1)
    {
        liItem.AddCssClass("disabled");
    }
    html.Append(liItem);


    for (var i = 1; i <= Model.TotalPages; i++)
    {
        var li = new TagBuilder("li");

        li.AddCssClass("page-item");
        if (i == Model.CurrentPage)
        {
            li.InnerHtml = @"<span class='page-link'>" + i +
                           @"<span class='sr-only'>(current)</span></span>";
        }
        else
        {
            li.InnerHtml = Ajax.ActionLink(i.ToString(), "List", new {category = categoryName, brand = brandName, page = i},
                new AjaxOptions {InsertionMode = InsertionMode.Replace, UpdateTargetId = "ProductList"},
                new {@class = "page-link ajax-page-link"}
                ).ToString();
        }

        html.Append(li);
    }

    {
        liItem = new TagBuilder("li")
        {
            InnerHtml = Ajax.ActionLink("Next", "List", new {category = categoryName, brand = brandName, page = Model.CurrentPage + 1},
                new AjaxOptions {InsertionMode = InsertionMode.Replace, UpdateTargetId = "ProductList"},
                new {@class = "page-link ajax-page-link"}
                ).ToString()
        };
        liItem.AddCssClass("page-item");
        if (Model.CurrentPage == Model.TotalPages)
        {
            liItem.AddCssClass("disabled");
        }
        html.Append(liItem);
    }
}

<nav class="col align-self-end">
    <ul class="pagination justify-content-center">
        @MvcHtmlString.Create(html.ToString())
    </ul>
</nav>

MVC/WebShop/Views/Product/SelectBrand.cshtml
@model IEnumerable<string>
@{
    var categoryName = HttpContext.Current.Request.QueryString.Get("category");
    var brandName = HttpContext.Current.Request.QueryString.Get("brand") ?? "All";
}
<div class="dropdown mb-5 mw-100">
    <button class="btn btn-secondary dropdown-toggle w-100" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @brandName
    </button>
<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    @Html.ActionLink("All", "List", new { category = (string)null, brand = (string)null }, new { @class = "dropdown-item" })
    @foreach (var item in @Model)
    {
        @Html.ActionLink(item, "List", new { category = categoryName, brand = item }, new { @class = "dropdown-item" })
    }
</div>
</div>

MVC/WebShop/Views/Product/SelectCategory.cshtml
@model IEnumerable<string>
@{
   var categoryName = HttpContext.Current.Request.QueryString.Get("category") ?? "All";
    var brandName = HttpContext.Current.Request.QueryString.Get("brand");
}
<div class="dropdown mb-5 mw-100">
    <button class="btn btn-secondary dropdown-toggle w-100" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @categoryName
    </button>
<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    @Html.ActionLink("All", "List", new { category = (string)null, brand = (string)null }, new {@class = "dropdown-item"})
    @foreach (var item in @Model)
    {
        @Html.ActionLink(item, "List", new { category = item, brand = brandName }, new { @class = "dropdown-item" })
    }
</div>
</div>