MVC/WebShop/Controllers/MenuController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class MenuController : Controller
    {
        private readonly List<MenuItemsVM> _menuItems;

        public MenuController()
        {
            _menuItems = new List<MenuItemsVM>
            {
                new MenuItemsVM {Name = "Home", Controller = "Home", Action = "Index", Active = string.Empty},
                new MenuItemsVM {Name = "Catalog", Controller = "Product", Action = "List", Active = string.Empty},
                new MenuItemsVM
                    {Name = "Categories & Brands", Controller = "Category", Action = "Common", Active = string.Empty},
                new MenuItemsVM
                    {Name = "Api", Controller = "Common", Action = "Index", Active = string.Empty},
            };
        }

        public ActionResult Index(string action = "Index", string controller = "Home")
        {
            if (User.IsInRole("admin"))
            {
                _menuItems.Add(new MenuItemsVM { Name = "Admin", Controller = "Admin", Action = "Index", Active = string.Empty });
            }
            var item = _menuItems.FirstOrDefault(g => g.Controller == controller);
            if (item != null)
            {
                item.Active = "active";
            }
            return PartialView(_menuItems);
        }
    }
}

MVC/WebShop/Views/Shared/AddToCart.cshtml
@model BLL.Models.Models.ProductDTO
@if (User.Identity.IsAuthenticated && User.IsInRole("user"))
{
    <button role="link" class="btn btn-primary col-4 add-cart-button" data-type=@Model.Number data-href =@Url.Action("AddToCart", "Cart", new {number = @Model.Number})>
        <i class="fa fa-cart-plus"></i>
    </button>
    <select class="custom-select col-4 float-right quantity_select">
        @for (var i = 1; i <= @Model.Quantity; i++)
        {
            <option value=@i>@i</option>
        }
    </select>
}

MVC/WebShop/Views/Shared/_Layout.cshtml
@using WebShop.Authentication
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
            @Html.ActionLink("MVC", "Index", "Home", null, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse float-left" id="navbarNavAltMarkup">
                @Html.Action("Index", "Menu", new
                {
                    controller = Request.RequestContext.RouteData.Values["Controller"],
                })
            </div>
            <div class="nav float-right">
                @Html.Action("Index", "Account")
            </div>
        </nav>
<div class="container mb-5">
    <div class="row">
        <div class="col-md-12">
            @RenderBody()
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom justify-content-between">
    <span class="text-light">&copy; @DateTime.Now.Year - My ASP.NET Application</span>
    <span class="text-light">@string.Format($"{(User as AuthUser)?.Email}")</span>
</nav>
@Scripts.Render("~/bundles/ajax")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/main")
@RenderSection("scripts", required: false)
</body>
</html>